### ISSUE TITLE
Fetching DID by handle fails

### ISSUE THREAD

**Issue by tdack** [skiniks/pds-explorer#1]
https://github.com/skiniks/pds-explorer/blob/fdd1896f313c9debb674de06d16ece1b1e03af3d/src/lib/atproto.ts#L8

The URL should be `https://${handle}/.well-known/atproto-did`

See: https://atproto.com/specs/handle#handle-resolution

**Comment by skiniks** [comment]
@tdack Thank you for your attention to detail! The URL you referenced (`/.well-known/atproto-did`) is indeed correct according to the AT Protocol specification for handle resolution. However, in this case, `/.well-known/did.json` is actually the correct endpoint because this particular code path is specifically handling `did:web` resolution, not AT Protocol handle resolution.

For `did:web` identifiers, the specification requires the DID document to be served at `/.well-known/did.json`. Our fallback to the bsky.social XRPC endpoint handles the AT Protocol handle resolution case.

So while you're absolutely right about what the AT Protocol spec says, in this specific context we need to keep using `did.json` to maintain `did:web` support.
